### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by dagilleland** [Programming-0101/Achievement-Unlocked#1]
Here's a rough idea of the general roadmap for the project. This is subject to change, but it should give you a good idea of what to expect.

- [x] Basic vite setup (Vanilla JS)
- [x] Create a basic badge
- [x] Create a basic badge with a custom icon (using Font Awesome)
- [x] List/search the available icons
- [ ] Export the badge
  - [ ] As a stand-alone Web Component
